; vi:ft=msp430
.section .vectors
        .word  RESET
        .word  RESET
        .word  RESET    ; PORT1
        .word  RESET    ; PORT2
        .word  RESET    ; USI
        .word  RESET    ; ADC10
        .word  RESET
        .word  RESET
        .word  RESET    ; TACCR1
        .word  RESET    ; TACCR0
        .word  RESET    ; WDT
        .word  RESET
        .word  RESET
        .word  RESET
        .word  RESET    ; NMI
        .word  RESET    ; POR

